version: '3'
services:
  neo4j:
    image: "neo4j:3.3"
  redis:
    image: "redis:4.0"    
  celery:
    build: 
      context: .
      dockerfile: celery
    depends_on:
      - neo4j
      - redis
    volumes:
      - database:/app/db/
  uwsgi:
    build: 
      context: .
      dockerfile: uwsgi
    depends_on: 
      - neo4j
      - redis
    ports: 
      - "8000:8000"
    volumes:
      - database:/app/db/
      - static:/static
  nginx:
    image: nginx
    depends_on: 
      - uwsgi
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/static
    ports: 
      - "8080:80"
volumes:
  database:
  static: